<template>
  <!-- PacMan for indicating loading -->
  <div class="loadingio-spinner-bean-eater-o5tefvffeqm">
    <div class="ldio-sweozsnwol">
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<style scoped type="text/css">
/**
 * LoadSpinner component for indicating loading in the form of PacMan.
 *
 * generated by https://loading.io/
 */
@keyframes ldio-sweozsnwol-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-sweozsnwol-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-sweozsnwol > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-sweozsnwol > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #f8b26a;
  animation: ldio-sweozsnwol-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-sweozsnwol > div:nth-child(2) div:nth-child(2) {
  animation: ldio-sweozsnwol-2 1s linear infinite;
}
.ldio-sweozsnwol > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-sweozsnwol-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-sweozsnwol > div:nth-child(1) {
  display: block;
}
.ldio-sweozsnwol > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #004aad;
  animation: ldio-sweozsnwol-3 1s linear infinite;
}
.ldio-sweozsnwol > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-sweozsnwol > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-sweozsnwol > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-o5tefvffeqm {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-sweozsnwol {
  width: 50%;
  height: 50%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;
}
.ldio-sweozsnwol div {
  box-sizing: content-box;
}
</style>
